fixed the readme instide of github because it is not working on local im so sad and depresso
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/ooowillexistsooo/octopus.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/ooowillexistsooo/octopus.git'

ITS IN GITIGNORE IM SOBBING